apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: llm-api
        image: default-route-openshift-image-registry.apps-crc.testing/oc-llm/llm-api:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: GOOGLE_APPLICATION_CREDENTIALS # Path to the google application credentials for vertex ai llm model
          value: "/app/credentials.json"
        - name: CV_FILE_PATH # Path to the cv file to use in RAG
          value: "/app/NayYaung_CV_2024_JK.docx"
        - name: API_KEY # Api key for react client to access this backend. NOT the api key for google vertex ai
          value: "AIzaSyD12"
        imagePullPolicy: Always