version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # Path to the google application credentials for vertex ai llm model
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      # Path to the cv file to use in RAG
      - CV_FILE_PATH=/app/NayYaung_CV_2024_JK.docx
      # Api key for react client to access this backend. NOT the api key for google vertex ai
      - API_KEY=AIzaSyD12 # In a production environment, it would have been come from database for client subscription